GET http://localhost:3001/todos
###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text" : "MOhid"
}
###

DELETE http://localhost:3001/todo/delete/64356d4e6d700114857f3477

###

PUT http://localhost:3001/todo/complete/64356db26d700114857f3489